host: 'localhost'
port: 9200
article_directory: '../generated_articles/UNH-bm25-ecmpsg.jsonl'
question_directory: 'question-for-extraction/tqa_v1_train.json'
mapping: |-
  {
      "mappings": {
          "sentence": {
              "dynamic": "false",
              "properties": {
                  "docId": {
                      "type": "keyword"
                  },
                  "text": {
                      "analyzer": "standard",
                      "type": "text",
                      "fields": {
                          "raw": {
                              "type": "keyword"
                          }
                      }
                  },
                  "tags": {
                      "type": "keyword"
                  }
              }
          }
      }
  }
